language: go
os:
  - linux
  - osx
sudo: false
go: "1.11"
matrix:
  include:
    - go: "1.10"
      os: linux
env: CGO_ENABLED=0
jobs:
  include:
    - stage: build
      script: echo build
    - stage: deploy
      script: echo deploy
