language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    - stage: coverage
      script: echo coverage
      if: type = push
      os: linux
    - os: osx
    - stage: deploy
      script: echo deploy
      if: type = push
script: echo test
