language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    - stage: coverage
      script: echo coverage
    - stage: deploy
      script: echo deploy
