language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
matrix:
  exclude:
    - go: "1.10"
      os: osx
env: CGO_ENABLED=0
jobs:
  include:
    - stage: coverage
      script: echo coverage
    - stage: deploy
      script: echo deploy
