language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    - stage: deploy
      name: coverage
      script: echo coverage
      if: type = push
      os: linux
    - name: coverage
      script: echo coverage
      if: type = push
      os: osx
    - name: deploy
      script: echo deploying for branch = $TRAVIS_BRANCH
      if: type = push
script: echo testing for branch = $TRAVIS_BRANCH
